name: "Reusable TagBot Workflow"

on:
  workflow_call:
    inputs:
      localregistry:
        description: "Add local registries hosted on GitHub. Specified by providing the url (https/ssh) to the repositories as a newline (\n) seperated list. User is responsible for setting up the necessary SSH-Keys to access the repositories if necessary."
        default: ""
        required: false
        type: string
    secrets:
      TAGBOT_TOKEN:
        required: true

jobs:
  TagBot:
    name: "Tag Versions"
    runs-on: ubuntu-latest

    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.localregistry }}
